"""Altcoin Momentum Agent — public API surface."""
from altcoin_agent.ai_engine import (
    AIVerdict,
    DeepSeekEngine,
    EngineError,
    SocialPost,
)
from altcoin_agent.fuser import (
    DEFAULT_RULE_WEIGHTS,
    Direction,
    FusedSignal,
    FuserConfig,
    ScoreFuser,
)
from altcoin_agent.risk import (
    AccountState,
    CCXTExecutor,
    DynamicLeverageConfig,
    ExchangeAdapter,
    GateDecision,
    OrderIntent,
    OrphanPosition,
    Position,
    PositionSizer,
    Reconciler,
    ReconcilerReport,
    RiskGate,
    RiskGateConfig,
    SizingResult,
    TrailingState,
    TrailingStopFSM,
    compute_dynamic_leverage,
)
from altcoin_agent.screener import (
    FundingAnomalyDetector,
    FundingSnapshot,
    Kline,
    LiquidityPool,
    LiquidityPoolAnalyzer,
    OISnapshot,
    OISurgeDetector,
    Screener,
    SignalEvent,
    SignalKind,
    VolumeSpikeDetector,
)

__all__ = [
    # screener
    "Screener",
    "SignalEvent",
    "SignalKind",
    "Kline",
    "FundingSnapshot",
    "OISnapshot",
    "LiquidityPool",
    "VolumeSpikeDetector",
    "FundingAnomalyDetector",
    "OISurgeDetector",
    "LiquidityPoolAnalyzer",
    # ai_engine
    "DeepSeekEngine",
    "AIVerdict",
    "SocialPost",
    "EngineError",
    # fuser
    "ScoreFuser",
    "FusedSignal",
    "FuserConfig",
    "Direction",
    "DEFAULT_RULE_WEIGHTS",
    # risk + execution
    "AccountState",
    "Position",
    "OrderIntent",
    "RiskGate",
    "RiskGateConfig",
    "GateDecision",
    "PositionSizer",
    "SizingResult",
    "DynamicLeverageConfig",
    "compute_dynamic_leverage",
    "TrailingStopFSM",
    "TrailingState",
    "Reconciler",
    "ReconcilerReport",
    "OrphanPosition",
    "CCXTExecutor",
    "ExchangeAdapter",
]
